### ISSUE TITLE
The CRD for AquaStarboard kind in 6.5.2 has invalid syntax

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/aqua-operator#127]
I think we have the same bug for other kinds as well where the `JSONPath` property should be replaced with `jsonPath`. In general, all CRDs migrated from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` should be revisited.

```console
kubectl apply -f https://raw.githubusercontent.com/k8s-operatorhub/community-operators/main/operators/aqua/6.5.2/aquastarboards.aquasecurity.github.io.crd.yaml
```
error: error validating "https://raw.githubusercontent.com/k8s-operatorhub/community-operators/main/operators/aqua/6.5.2/aquastarboards.aquasecurity.github.io.crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[0]): unknown field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[0]): missing required field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[1]): unknown field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[1]): missing required field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[2]): unknown field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[2]): missing required field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[3]): unknown field "JSONPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition, ValidationError(CustomResourceDefinition.spec.versions[0].additionalPrinterColumns[3]): missing required field "jsonPath" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceColumnDefinition]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by semyonmor** [comment]
@danielpacak it was fixed in `v6.5.3`
