### ISSUE TITLE
Is not possible to deploy Certified Operator in OCP 4.9.24

### ISSUE THREAD

**Issue by tectime** [aquasecurity/aqua-operator#128]
Is not possible to deploy Certified Operator in OCP 4.9.24

After installing Aqua Operator 6.5 Certified through OperatorHub, I tried to install the Aqua CSP component, but during the process, we are getting the error below:

{"level":"error","ts":1647610796.241242,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AquaStarboard.aquasecurity.github.io","error":"no matches for kind \"AquaStarboard\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controlle...
{"level":"error","ts":1647610796.2414546,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"AquaStarboard\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\taqua-operator/cmd/manager/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

![image](https://user-images.githubusercontent.com/28829687/159014405-b6623a5b-a3da-41d8-a33e-fd69a2c00058.png)

Full log:

{"level":"info","ts":1647610768.090577,"logger":"cmd","msg":"Operator Version: 1.0.2"}
{"level":"info","ts":1647610768.0906022,"logger":"cmd","msg":"Go Version: go1.13.6"}
{"level":"info","ts":1647610768.0906055,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1647610768.0906081,"logger":"cmd","msg":"Version of operator-sdk: v0.15.1"}
{"level":"info","ts":1647610768.090994,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1647610770.4129207,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1647610770.4129426,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1647610772.7180617,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1647610772.7183123,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1647610789.2678258,"logger":"cmd","msg":"Could not generate and serve custom resource metrics","error":"discovering resource information failed for AquaStarboard in aquasecurity.github.io/v1alpha1: apiVersion aquasecurity.github.io/v1alpha1 and kind AquaStarboard not found available in Kubernetes cluster"}
{"level":"info","ts":1647610791.6145015,"logger":"metrics","msg":"Metrics Service object updated","Service.Name":"aqua-operator-metrics","Service.Namespace":"aqua"}
{"level":"info","ts":1647610793.9360304,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"servicemonitors.monitoring.coreos.com \"aqua-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
{"level":"info","ts":1647610793.9361176,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1647610793.9363482,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"AquaStarboard-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.9366558,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1647610793.9367726,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquascanner-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.936832,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquagateway-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.936878,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquakubeenforcer-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.9369354,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquaserver-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.9370446,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquacsp-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.9371362,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquadatabase-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1647610793.937285,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"aquaenforcer-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1647610796.241242,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AquaStarboard.aquasecurity.github.io","error":"no matches for kind \"AquaStarboard\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controlle...
{"level":"error","ts":1647610796.2414546,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"AquaStarboard\" in version \"aquasecurity.github.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\taqua-operator/cmd/manager/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

![image](https://user-images.githubusercontent.com/28829687/159013829-126bfbb9-79f2-4684-8a6c-9837df55eaf1.png)

Thank you
Robson Messias
Aqua Support

**Comment by danielpacak** [comment]
I think it's related to #127

**Comment by semyonmor** [comment]
@tectime and @danielpacak we are working on fix for both issues

**Comment by semyonmor** [comment]
@tectime it was fixed in latest certified operator and community 6.5.3
Can you please check and if everything is ok, we will close the issue

**Comment by semyonmor** [comment]
This one was fixed
Closing the issue
