### ISSUE TITLE
Aqua Operator Helm repo link 404s

### ISSUE THREAD

**Issue by agilgur5** [aquasecurity/aqua-operator#5]
In the Installation docs, it says you can [install `aqua-operator` via Helm](https://github.com/aquasecurity/aqua-operator/blob/master/docs/Installation.md#installation-via-helm). The link takes you to https://github.com/aquasecurity/aqua-operator-helm, which 404s.

It doesn't exist in the [`aqua-helm` repo](https://github.com/aquasecurity/aqua-helm) either, and per https://github.com/aquasecurity/aqua-helm/issues/96 no `aqua-operator` Chart exists on https://helm.aquasec.com either.

**Comment by amirgabrieli** [comment]
Thank you for pointing this up. We will fix it!

**Comment by rshmiel** [comment]
@agilgur5 closing this issue. this section was removed from the documentation as we are not supporting HELM deployment by the operator.
Thanks for reporting.
