### ISSUE TITLE
Add limit support to enforcer CR

### ISSUE THREAD

**Issue by together-var** [aquasecurity/aqua-operator#51]
Hi,

according to your enterprise documentation:
https://docs.aquasec.com/docs/advanced-deployment-architecture#findings-1
https://docs.aquasec.com/docs/sizing-guide#recommendations

Someone should be able to restrict ressource consumption for the different components. 
When deploying EnforcerCR like it is now, the consumed RAM is reaching ~3GB per Enforcer which is quite high. 

I am missing possibility to attach limits and requests to the CRs.

**Comment by guyyakir** [comment]
you can define the resources for the enforcer in the AquaEnforcer CR .spec.deploy.resources

you can see an example here https://github.com/aquasecurity/aqua-operator/blob/6.0.0/deploy/crds/operator_v1alpha1_aquaenforcer_cr.yaml
