### ISSUE TITLE
Possibilities for automation?

### ISSUE THREAD

**Issue by together-var** [aquasecurity/aqua-operator#72]
Hi,

how can we make use of the operator in a fully automated installation manner via some pipeline?
We discovered two points that are unclear how they can be automated, or if it's even possible.

1. Image Ref in Operator-certified-deployment. 
You want the user to place sha256 digest there. Why is this needed? Where to obtain the information

2. No Scanneruser can be provided to Server CR, hence ScannerCR can't be deployed directly afterwards
It seems that ServerCR is missing an option to provide ScannerUser via e.g. secret and then reference same secret in scannerCR to have an automated deployment. For now it looks like customer still has to write it's own pipeline / REST commands to inject scanner user in running server. Is this the case?

Thanks in advance.

**Comment by guyyakir** [comment]
Hey

1. not sure what do you mean by providing image Ref ? the certified operator installation is done by the Operator Life cycle Manager (OLM), for the certified operator the Aqua images are built-in inside the operator and can not be changed.

2. the operator is used for deploying Aqua and doesn't support any REST operations (not yet at least) so creating users is not a supported operation using the operator.
like you mentioned, after the serverCR is installed, a REST call to create a scanner user can be made, and after that deploying the ScannerCR using the scanner user name and password created.

**Comment by together-var** [comment]
Hello,

if it's okay I would seperate my response with numbers according to your answer.

1. What I mean with ImageRef is from https://github.com/aquasecurity/aqua-operator/blob/master/deploy/operator-certified.yaml:
`          image: "registry.connect.redhat.com/aquasec/operator@<digest>"
...
Set the related images name with digest            
- name: RELATED_IMAGE_DATABASE              value: "registry.connect.redhat.com/aquasec/database@&lt;digest&gt;"            
- name: RELATED_IMAGE_GATEWAY              value: "registry.connect.redhat.com/aquasec/gateway@&lt;digest&gt;"            
- name: RELATED_IMAGE_SERVER              value: "registry.connect.redhat.com/aquasec/console@&lt;digest&gt;"           
-  name: RELATED_IMAGE_SCANNER              value: "registry.connect.redhat.com/aquasec/scanner@&lt;digest&gt;"            
- name: RELATED_IMAGE_ENFORCER              value: "registry.connect.redhat.com/aquasec/enforcer@&lt;digest&gt;"
`

Why is this needed? For my deployment to work (i.e. to apply the deployment and that a running operator container is the result) I had to obtain the digest by hand by visiting Red Hat container cataloge and copy the digest after searching for your images. Why? I would expect the operator definition to work just by applying it to a cluster and that it reffers to know Imagestreams of yours in the Red Hat registry.

2. I am aware that it does not support any REST automation. Automating it that way was just an idea of mine as you seem to not support automatic installation of a full Aqua CSP stack. 
What I was actually intending for is to ask, why it's not possible to give a user the possibility to inject a ScannerUser to the Server at startup by ENV var or similar. If Aqua would build in such function to their Server Container, then kubernetes design pattern would be followed and a full Aqua CSP stack could be enrolled automatically via operator like a charm

**Comment by guyyakir** [comment]
hey

1. in no point in our documentation there is a mention to install the operator via this YAML. this YAML is old and not maintained. the operator install should be done by the Operator Hub.

2. adding capabilities to the Aqua operator such as creating a scanner user is on our roadmap. but for the existing operators this functionality won't be available.
