### ISSUE TITLE
Allow to define Deployment criterias on Enforcer when using AquaCSP CRD

### ISSUE THREAD

**Issue by gcuisinier** [aquasecurity/aqua-operator#9]
Hello,

In order to define where we want to deploy the Enforcer in a Cluster when using AquaCSP object, it should be interesting to define NodeSelector, but also Affinity or Tolerations on the Enforcer.

And in the same time, it should be interesting to allow defining resources limites and request also.

**Comment by semyonmor** [comment]
@gcuisinier 
due to product decision, those parameters could be define throw the Enforcer CRD and not via the AquaCSP
