### ISSUE TITLE
mTLS does not work in operator 

### ISSUE THREAD

**Issue by together-var** [aquasecurity/aqua-operator#90]
Hi,

based on discussion and enterprise tickets made in the past we did accomplished the mTLS setup within a normal legacy deployment. 

Now, we want to accomplish mTLS within a Operator based deployment too. For that, we used the AquaCSP.cr and provided inside ENV vars for server/gateway/enforcer as well as volumes and volumeMounts to grab respective secret objects for each component.

By that, I encountered that mTLS does work for the server / gateway side of things. However, I also encountered that it does not work for the enforcer / agent site. 
For the agents I also relied on some common sense of mine, as you don't have documented the TLS mount for the enforcer part. I was providing now the agent secret via volume mounts and ENV vars like I do for the other components - as it is also documented here in the server / gateway sections on the files in github-

It seems obvious to me that mTLS does not work, when agents don't have ENV vars and Secret mount set. 

Please tell me what format the operator expects on the agents section to mount secrets and get mTLS to work. 

Greetings

**Comment by guyyakir** [comment]
hey,

I'm not quite sure i got your question.
![image](https://user-images.githubusercontent.com/70201789/136050370-856adeb5-daed-4d9f-a858-ee5bb0287920.png)

we can set mTLS by defining the volume/volumeMounts with the files and relevant environment variables according to the Aqua documentions.

this should provide agent->gateway and gateway->server mTLS connection.

**Comment by together-var** [comment]
hi,

I revised the documentation and had the same impression as you. 
However the agents do not get the volume attached nor env vars set to take advantag of the secret containing the TLS cert, key, rootCA.

Maybe I'm just missing something?
Attached my enforcer CSP.cr section

`  enforcer:
    enforcerMode: audit
    env:
    - name: "AQUA_PRIVATE_KEY"
      value: "/opt/aquasec/ssl/agent.key"
    - name: "AQUA_TLS_VERIFY"
      value: 'true'
    - name: "RESTART_CONTAINERS"
      value: 'no'
    - name: "AQUA_LOGICAL_NAME"
      value: "octest"
    - name: "AQUA_PUBLIC_KEY"
      value: "/opt/aquasec/ssl/agent.crt"
    - name: "AQUA_ROOT_CA"
      value: "/opt/aquasec/ssl/rootCA.crt"
    - name: "AQUA_ENFORCER_SCANNING_MEMORY_LIMIT"
      value: '500'
    secret:
      name: enforcer-token
      key: token
    image:
      pullPolicy: Always
      registry: registry.aquasec.com
      repository: enforcer
      tag: '6.2'
    volumes:
      - name: aqua-grpc-enforcer
        secret:
          secretName: aqua-grpc-enforcer
    volumeMounts:
        - mountPath: /opt/aquasec/ssl
          name: aqua-grpc-enforcer
          readOnly: true      `

**Comment by guyyakir** [comment]
hey,

OK i understand now,

you are trying to set those parameters using the AquaCSP .spec.enforcer, which doesn't support that. the .spec.enforcer supports a small set of attributes and not all the possibilities of the AquaEnforcer CR.

the way it would work is deploying an AquaEnforcer CR.

**Comment by together-var** [comment]
Hi,

ahhh that sounds valid. I thought that this features works via the CSP.cr
I will take the enforcer.cr then and get back or close if needed.

Thanks

**Comment by semyonmor** [comment]
@cc-togerhar can we close this issue or still relevant?
