### ISSUE TITLE
runAsNonRoot not working

### ISSUE THREAD

**Issue by together-var** [aquasecurity/aqua-operator#91]
Hi,

we have encountered that all the pods run with a securitycontextconstraint (Openshift equivalent for K8s psp's) of "privileged", which is equivalent to root.

After review of your example CRs we found the option to set runAsNonRoot to true. 

Expected result:
All pods run in the restricted SCC of Openshift

Actual result:
All your pods run still in privileged mode

Question:
Is there a way to force usage of the restricted SCC in operator based deployments of yours, like it is possible for via legacy yamls?

Thanks in advance
Greetings

**Comment by guyyakir** [comment]
hey,

currently all the Aqua components are running with the "privileged" SCC, as the operator create a binding between the "aqua-sa" service account and privileged SCC on installation.

there is a way (not officially supported) for the community operator, to run the Aqua components with "aqua-scc" SCC, but that haven't been tested properly, and might effect the seamless upgrades mechanism.

**Comment by together-var** [comment]
Hey,

for sure Aqua enforcers need the priv SCC and operator making the binding is needed. 
However, server / GW /Scanner don't need that SCC.

Also technique from Openshift should pull the least privileges, but matching, SCC to all pods. As the aqua-sa is bound to other SCC too, openshift should handle attachment of less privileges SCCs according to the deployment yamls the operator generates.

For example:
If you have in the scanner deployment the 'RunAsUser: 0', then the priv SCC is the only one providing that ability and openshift will assign it. 
If you don't specifiy that, but leave the old Docker.sock mount via hostpath in the scanner deployment, then OCP attached 'hostaccess'.
If you also have no hostpath in the yaml definition, then OCP will assign the least privileged 'restricted' SCC to a pod. 

As it is achieveable for non operator deployments of Aqua to get every component, except agents, to run under restricted SCC I would like to get the same experience with the operator deployment. 

Greetings

**Comment by guyyakir** [comment]
hey,

currently we are using the same SCC for all Aqua components (also on non operator deployments).

i suggest to raise it with aqua support as a bug/RFE and we will investigate breaking each component to a different SCC.

**Comment by semyonmor** [comment]
@cc-togerhar 
Please open RFE for this request with explanation what are you expected to receive and we will add it to our roadmap
